coffee_list = (
    {"drink":"Bedchamber", "pic":"https://static.wikia.nocookie.net/coffeetalk/images/4/43/Bedchamber.png", "desc":"A cup for those longing for a deep slumber."},
    {"drink":"Bitter Heart", "pic":"https://static.wikia.nocookie.net/coffeetalk/images/c/c4/Bitter_Heart.png", "desc":"Shadows that will help you try to hide."},
    {"drink":"Black Lemon", "pic":"https://static.wikia.nocookie.net/coffeetalk/images/7/72/Black_Lemon.png", "desc":"A perfect - if unlikely - combination of sour and bitter."},
    {"drink":"Black Magic", "pic":"https://static.wikia.nocookie.net/coffeetalk/images/e/e9/Black_Magic.png", "desc":"Sweet, cool, and magically wakes you up."},
    {"drink":"Caffé Latte", "pic":"https://static.wikia.nocookie.net/coffeetalk/images/b/b7/Caff%C3%A9_Latte.png", "desc":"A caffeine boost dominated by milk."},
    {"drink":"Cappuccino", "pic":"https://static.wikia.nocookie.net/coffeetalk/images/d/db/Cappuccino.png", "desc":"Italian delight."},
    {"drink":"Chocobee Miruku", "pic":"https://static.wikia.nocookie.net/coffeetalk/images/6/65/Chocobee_Miruku.png", "desc":"Sweet, nourishing, healthy, chocolate."},
    {"drink":"Cough Syrup", "pic":"https://static.wikia.nocookie.net/coffeetalk/images/3/31/Cough_Syrup.png", "desc":"A cure for a sore throat."},
    {"drink":"Dark Chocolate", "pic":"https://static.wikia.nocookie.net/coffeetalk/images/4/42/Dark_Chocolate.png", "desc":"A warm and calming darkness."},
    {"drink":"Espresso", "pic":"https://static.wikia.nocookie.net/coffeetalk/images/a/ad/Espresso.png", "desc":"Blacker than a moonless night, hotter and more bitter than hell itself."},
    {"drink":"Gala Had", "pic":"https://static.wikia.nocookie.net/coffeetalk/images/0/09/Gala_Had.png", "desc":"Ginger chai latte, good to calm yet warm your nerve."},
    {"drink":"Ginger Latte", "pic":"https://static.wikia.nocookie.net/coffeetalk/images/2/2d/Ginger_Latte.png", "desc":"Warm energy boost, perfect for a cold evening."},
    {"drink":"Gingerbread Coffee", "pic":"https://static.wikia.nocookie.net/coffeetalk/images/a/a2/Gingerbread_Coffee.png", "desc":"Sweetened with brown sugar to satisfy the cookie monster."},
    {"drink":"Green Tea Latte", "pic":"https://static.wikia.nocookie.net/coffeetalk/images/5/50/Green_Tea_Latte.png", "desc":"Both sweet and savory, with a hint of bitterness for the heart."},
    {"drink":"Jahe Tubruk", "pic":"https://static.wikia.nocookie.net/coffeetalk/images/f/ff/Jahe_Tubruk.png", "desc":"Ginger presides over the ground coffee at the bottom of the cup; originally from Indonesia."},
    {"drink":"Le Menthol", "pic":"https://static.wikia.nocookie.net/coffeetalk/images/0/0b/Le_Menthol.png", "desc":"Sour and cool, with a hint of home."},
    {"drink":"Lemony Snippet", "pic":"https://static.wikia.nocookie.net/coffeetalk/images/5/59/Lemony_Snippet.png", "desc":"A fortunate tale in a cup."},
    {"drink":"Marrakech", "pic":"https://static.wikia.nocookie.net/coffeetalk/images/5/51/Marrakech.png", "desc":"Fresh and healthy drink from Morocco."},
    {"drink":"Masala Chai", "pic":"https://static.wikia.nocookie.net/coffeetalk/images/0/03/Masala_Chai.png", "desc":"Spiced tea from Southern Asia."},
    {"drink":"Midsummer Night’s Dream", "pic":"https://static.wikia.nocookie.net/coffeetalk/images/1/16/Midsummer_Night%E2%80%99s_Dream.png", "desc":"Sweet and memorable, like summertime blues."},
    {"drink":"Milky Way", "pic":"https://static.wikia.nocookie.net/coffeetalk/images/e/ef/Milky_Way.png", "desc":"Sweet and cool, like outer space."},
    {"drink":"Russian Tea", "pic":"https://static.wikia.nocookie.net/coffeetalk/images/a/a5/Russian_Tea.png", "desc":"Despite the name, it’s a totally American drink."},
    {"drink":"Shai Adeni", "pic":"https://static.wikia.nocookie.net/coffeetalk/images/8/8e/Shai_Adeni.png", "desc":"Sweet spicy chai latte from the town of Aden, Yemen."},
    {"drink":"Shin Genmaicha", "pic":"https://static.wikia.nocookie.net/coffeetalk/images/a/a2/Shin_Genmaicha.png", "desc":"A variation of the Japanese brew, mixing the brown rice with ginger."},
    {"drink":"Spanish Sahara", "pic":"https://static.wikia.nocookie.net/coffeetalk/images/9/9a/Spanish_Sahara.png", "desc":"Warm and cozy, just like a day in Barcelona."},
    {"drink":"Spiced Lady", "pic":"https://static.wikia.nocookie.net/coffeetalk/images/3/34/Spiced_Lady.png", "desc":"A chocolate drink, extremely popular in the 90’s."},
    {"drink":"STMJ", "pic":"https://static.wikia.nocookie.net/coffeetalk/images/8/86/STMJ.png", "desc":"Warm booster made of susu (milk), telur (egg), madu (honey), and jahe (ginger); from Indonesia."},
    {"drink":"Sugar and Spice", "pic":"https://static.wikia.nocookie.net/coffeetalk/images/c/c0/Sugar_and_Spice.png", "desc":"Spicy, sweet, and natural bliss in a cup."},
    {"drink":"Teh Tarik", "pic":"https://static.wikia.nocookie.net/coffeetalk/images/4/4b/Teh_Tarik.png", "desc":"Tea with milk, mixed by pouring the two repeatedly between cups; originally from Malaysia."},
    {"drink":"The Grinch", "pic":"https://static.wikia.nocookie.net/coffeetalk/images/7/73/The_Grinch.png", "desc":"Green, spicy, and not everyone's cup of tea."},
)
